



services:
  exchange-rate-service:
    build: .
    image: exchange_service:latest
    container_name: exchange_service
    ports:
      - "8080:8080"
    networks:
      - monitoring


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9091:9090"
    networks:
      - monitoring


networks:
  monitoring:
    driver: bridge
  